<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>netflix-mini</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>netflix-mini</name>

    <modules>
        <module>ApiGateway</module>
        <module>AuthService</module>
        <module>DiscoverService</module>
        <module>HomePageService</module>
        <module>StreamingService</module>
        <module>UploadService</module>
    </modules>

    <!-- QUẢN LÝ VERSION (KHÔNG CHỨA DEPENDENCY CHẠY) -->
    <properties>
        <java.version>21</java.version>
        <spring-boot.version>4.0.5</spring-boot.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>