server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      database: 0
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: homepage-route
              uri: lb://homepage-service
              predicates:
                - Path=/home/**

            - id: autharoute
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
